<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <WorldBoxDir Condition="'$(WorldBoxDir)' == ''">.</WorldBoxDir>
    <AssemblyName>WorldBoxMod.Template</AssemblyName>
    <RootNamespace>WorldBoxMod.Template</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="MinimalWorldBoxMod.cs" />
    <None Include="mod.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(WorldBoxDir)\worldbox_Data\StreamingAssets\mods\NML\Assembly-CSharp-Publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="NeoModLoader">
      <HintPath>$(WorldBoxDir)\worldbox_Data\StreamingAssets\mods\NeoModLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(WorldBoxDir)\worldbox_Data\StreamingAssets\mods\NML\Assemblies\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(WorldBoxDir)\worldbox_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
